// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    // seed: 'node prisma/seed.js', // ← use JS seed
    seed: 'node --require ts-node/register prisma/seed.ts',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
